### ISSUE TITLE
Documentation not correct

### ISSUE THREAD

**Issue by steowens** [ALIZE-Speaker-Recognition/alize-core#1]
The INSTALL file in the project root is misinformative.  It does not appear that the source was checked in with the ./configure script generated and the documentation does not mention the preliminary automake steps needed to actually generate the ./configure file.

**Comment by tevamerlin** [comment]
Thanks for bringing this to our attention. The use of automake was mentioned in the README file but forgotten in the INSTALL file. I’ve updated the files with (hopefully) better installation instructions.
