### ISSUE TITLE
Installation issues : .compile missing and lib folder not created

### ISSUE THREAD

**Issue by rafaelvalle** [ALIZE-Speaker-Recognition/alize-core#3]
Can you add a line on the readme file explaining that automake --add-dependencies should be used in case .compile is missing and that lib folder should be created in case it's missing?

**Comment by tevamerlin** [comment]
I’ve added a note in the readme file about using automake --add-missing, and I’ve modified Makefile.am so that the lib folder is created before moving the library there.
